
name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  google_fonts: ^6.1.0
  share_plus: ^7.0.0
  shared_preferences: ^2.0.15
  in_app_purchase: ^3.0.0
  intl: ^0.20.2
  image_picker: ^1.2.1
  flutter_local_notifications: ^19.5.0
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon2.png"
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
